In [2]:
# open a csv file and make it a df

import pandas as pd
import numpy as np

# open the csv file
df = pd.read_csv('shiraz_city_pois_attraction_modified_OH_____.csv')

In [3]:
df

,name,coordinates,open_time,close_time,spending_time,slug_category,latitude,longitude
0,eram-garden-shiraz,"[29.6360623, 52.5251428]",480,1230,120,urban_attractions,29.636062,52.525143
1,natural-history-technology-museum,"[29.5925335, 52.5721767]",480,840,120,urban_attractions,29.592533,52.572177
2,afif-abad-garden-military-museum,"[29.6231997, 52.4983724]",540,1080,120,urban_attractions,29.623200,52.498372
3,persepolis-of-shiraz,"[29.9355247, 52.89211299999999]",480,1050,120,urban_attractions,29.935525,52.892113
4,nasir-al-mulk-mosque-shiraz,"[29.6085479, 52.5486555]",420,1020,120,urban_attractions,29.608548,52.548656
...,...,...,...,...,...,...,...,...
178,besat-park-shiraz,"[29.6194811, 52.501335]",570,1290,120,urban_attractions,29.619481,52.501335
179,baba-abr-icecream-shiraz,"[29.6328026, 52.5390032]",540,1590,120,urban_attractions,29.632803,52.539003
180,salamat-walkway-shiraz,"[29.6773251, 52.4817861]",1110,1560,120,urban_attractions,29.677325,52.481786
181,taknaz-shopping-center-shiraz,"[29.6324673, 52.5537672]",540,1260,180,shopping,29.632467,52.553767
182,negin-fars-shopping-center-adel-abad-shiraz,"[29.5805727, 52.5090539]",510,1440,180,shopping,29.580573,52.509054

In [4]:
type(df['coordinates'][0])

str